"""Cross-dataset (zero-shot transfer) figure and appendix table from the
results of scripts/crossdataset_eval.py, contrasted with the in-domain
matched AP of the same classes from the suite evaluations. Axis labels are
German because the figures go into the German thesis; style and color
definitions live in master/thesis_main.tex.

Usage (from the repo root):  uv run python scripts/make_ood_figure.py
"""

from __future__ import annotations

import glob
import json
import statistics as st
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
CROSS = REPO / "experiments/analysis/crossdataset"
SUITES = REPO / "experiments/suites"
OUT = REPO.parent / "master/abbildungen"

CLS = ["military_tank", "military_aircraft", "military_helicopter"]
CLS_LABEL = ["Panzer", "Mil. Flugzeug", "Helikopter"]
MODELS = ["nano", "small", "base", "medium", "large"]
MODEL_LABEL = {"nano": "Nano", "small": "Small", "base": "Base", "medium": "Medium", "large": "Large"}
SUITE_BY_ITER = {"iter1": "thesis_l40_main", "iter4": "thesis_l40_iter4"}

HEADER = "% Generated by code/scripts/make_ood_figure.py\n"


def de(value: float, precision: int = 3) -> str:
    return f"{value:.{precision}f}".replace(".", ",")


def indomain(suite: str, history_key: str) -> dict[str, float]:
    vals: dict[str, list[float]] = {c: [] for c in CLS}
    for path in glob.glob(str(SUITES / suite / "model_*/seed_*/det_lora/evaluation.json")):
        data = json.load(open(path))
        history = data[history_key]
        final = str(max(int(k) for k in history))
        ap = history[final]["metrics"].get("AP_per_class@0.5", {})
        for c in CLS:
            if c in ap:
                vals[c].append(ap[c])
    return {c: st.mean(v) for c, v in vals.items() if v}


def ood_runs(suite: str) -> list[dict]:
    return [json.load(open(p)) for p in sorted(glob.glob(str(CROSS / f"{suite}_*.json")))]


def ood_matched_mean(runs: list[dict]) -> dict[str, float]:
    return {
        c: st.mean([r["matched"][c]["AP@0.5"] for r in runs]) for c in CLS
    }


def write_figure(ood_matched: dict[str, dict[str, float]], ood_mixed: dict[str, dict[str, float]]) -> None:
    series = [
        ("Gematcht It.~1", "plotFineTuning!45", ood_matched["iter1"]),
        ("Gematcht It.~4", "plotDetLoRA!45", ood_matched["iter4"]),
        ("Gemischt It.~1", "plotFineTuning", ood_mixed["iter1"]),
        ("Gemischt It.~4", "plotDetLoRA", ood_mixed["iter4"]),
    ]
    plots = []
    for label, color, vals in series:
        coords = " ".join(f"({i},{vals[c]:.3f})" for i, c in enumerate(CLS))
        plots.append(f"\\addplot[fill={color}, draw=none] coordinates {{{coords}}};")
        plots.append(f"\\addlegendentry{{{label}}}")
    tex = (
        HEADER
        + "\\begin{tikzpicture}\n\\begin{axis}[\n"
        + "  thesisplot,\n  width=0.9\\textwidth, height=68mm,\n"
        + "  ybar, bar width=9pt,\n"
        + "  xtick={0,1,2},\n"
        + "  xticklabels={" + ",".join(CLS_LABEL) + "},\n"
        + "  ymin=0, ymax=1.0,\n"
        + "  ylabel={AP@0,5 (Cross-Dataset)},\n"
        + "  nodes near coords={\\pgfmathprintnumber[fixed, fixed zerofill, precision=2, use comma]{\\pgfplotspointmeta}},\n"
        + "  every node near coord/.append style={font=\\tiny, rotate=90, anchor=west},\n"
        + "  legend columns=2,\n"
        + "  legend style={at={(0.5,1.03)}, anchor=south},\n]\n"
        + "\n".join(plots)
        + "\n\\end{axis}\n\\end{tikzpicture}\n"
    )
    (OUT / "erg_ood_transfer.tex").write_text(tex, encoding="utf-8")


def write_pervariant_table() -> None:
    lines = [
        HEADER.rstrip(),
        "\\begin{tabular}{lcccc}",
        "\\hline",
        "\\textbf{Variante} & \\textbf{Panzer} & \\textbf{Mil. Flugzeug} & "
        "\\textbf{Helikopter} & \\textbf{Gemischt (mAP@0,5)} \\\\",
        "\\hline",
    ]
    for model in MODELS:
        runs = [
            json.load(open(p))
            for p in sorted(glob.glob(str(CROSS / f"thesis_l40_iter4_{model}_seed*.json")))
        ]
        if not runs:
            continue
        cells = [de(st.mean([r["matched"][c]["AP@0.5"] for r in runs])) for c in CLS]
        mixed = de(st.mean([r["mixed"]["mAP@0.5_present"] for r in runs]))
        lines.append(f"{MODEL_LABEL[model]} & " + " & ".join(cells) + f" & {mixed} \\\\")
    lines += ["\\hline", "\\end{tabular}"]
    (OUT / "tab_ood_pervariant.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    indom = {key: indomain(suite, "matched_history") for key, suite in SUITE_BY_ITER.items()}
    indom_mixed = {key: indomain(suite, "mixed_history") for key, suite in SUITE_BY_ITER.items()}
    ood_data = {key: ood_runs(suite) for key, suite in SUITE_BY_ITER.items()}
    for key, runs in ood_data.items():
        print(f"{key}: {len(runs)} OOD-Läufe")
    ood = {key: ood_matched_mean(runs) for key, runs in ood_data.items() if runs}
    ood_mixed = {
        key: {c: st.mean([r["mixed"]["AP_per_class@0.5"][c] for r in runs]) for c in CLS}
        for key, runs in ood_data.items()
        if runs
    }
    if len(ood) < 2:
        raise SystemExit("OOD-Ergebnisse unvollständig; erst crossdataset_eval.py laufen lassen")
    write_figure(ood, ood_mixed)
    write_pervariant_table()

    summary = {
        "indomain_matched_ap50": indom,
        "indomain_mixed_ap50": indom_mixed,
        "ood_matched_ap50": ood,
        "ood_matched_ap5095": {
            key: {c: st.mean([r["matched"][c]["AP@0.5:0.95"] for r in runs]) for c in CLS}
            for key, runs in ood_data.items()
        },
        "ood_mixed_map50_present": {
            key: st.mean([r["mixed"]["mAP@0.5_present"] for r in runs])
            for key, runs in ood_data.items()
        },
        "ood_mixed_ap50_per_class": {
            key: {
                c: st.mean([r["mixed"]["AP_per_class@0.5"][c] for r in runs]) for c in CLS
            }
            for key, runs in ood_data.items()
        },
        "n_runs": {key: len(runs) for key, runs in ood_data.items()},
    }
    out_json = REPO / "experiments/analysis/crossdataset_summary.json"
    out_json.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print(f"[OK] Figure/Tabelle nach {OUT}, Zusammenfassung nach {out_json}")


if __name__ == "__main__":
    main()
