"""Figure for design iteration 2 (symmetric hard negatives) as a native
pgfplots graphic: per-class mixed AP@0.5, forward-only (thesis_l40_main)
vs. symmetric (thesis_l40_symhn), averaged over five model variants and
three seeds. Axis labels are German because the figure goes into the German
thesis; style and color definitions live in master/thesis_main.tex.

Usage (from the repo root):  uv run python scripts/make_symhn_figure.py
"""

from __future__ import annotations

import glob
import json
import statistics as st
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SUITES = REPO / "experiments/suites"
OUT = REPO.parent / "master/abbildungen"
OUT.mkdir(parents=True, exist_ok=True)

CLASSES = [
    "military_tank",
    "military_truck",
    "military_aircraft",
    "military_helicopter",
    "civilian_car",
    "civilian_aircraft",
]
CLASS_LABEL = {
    "military_tank": "Panzer",
    "military_truck": "Mil. LKW",
    "military_aircraft": "Mil. Flugzeug",
    "military_helicopter": "Helikopter",
    "civilian_car": "Ziv. PKW",
    "civilian_aircraft": "Ziv. Flugzeug",
}

MODELS = ["nano", "small", "base", "medium", "large"]
MODEL_LABEL = ["Nano", "Small", "Base", "Medium", "Large"]


def mixed_map_per_variant(suite: str) -> dict[str, tuple[float, float]]:
    """Mixed mAP@0.5 and mAP@0.5:0.95 per model variant, averaged over seeds."""
    per_variant: dict[str, tuple[float, float]] = {}
    for model in MODELS:
        map5, map5095 = [], []
        pattern = str(SUITES / suite / f"model_{model}/seed_*/det_lora/evaluation.json")
        for path in glob.glob(pattern):
            data = json.load(open(path))
            mixed_history = data["mixed_history"]
            final_task = str(max(int(k) for k in mixed_history))
            metrics = mixed_history[final_task]["metrics"]
            map5.append(metrics["mAP@0.5"])
            map5095.append(metrics["mAP@0.5:0.95"])
        if map5:
            per_variant[model] = (st.mean(map5), st.mean(map5095))
    return per_variant


def _de(value: float) -> str:
    return f"{value:.3f}".replace(".", ",")


def _de_signed(value: float) -> str:
    return f"{value:+.3f}".replace(".", ",").replace("+", "$+$").replace("-", "$-$")


def write_per_variant_table() -> None:
    """Write the LaTeX table for the per-variant Track A comparison."""
    forward = mixed_map_per_variant("thesis_l40_main")
    symmetric = mixed_map_per_variant("thesis_l40_symhn")
    lines = [
        r"\begin{tabularx}{\textwidth}{@{}l*{6}{>{\centering\arraybackslash}X}@{}}",
        r"\hline",
        r" & \multicolumn{3}{c}{\textbf{Gemischt mAP@0,5}} & \multicolumn{3}{c}{\textbf{Gemischt mAP@0,5:0,95}} \\",
        r"\textbf{Variante} & Iter.\ 1 & Iter.\ 2 & $\Delta$ & Iter.\ 1 & Iter.\ 2 & $\Delta$ \\",
        r"\hline",
    ]
    for model, label in zip(MODELS, MODEL_LABEL):
        f5, f9 = forward[model]
        s5, s9 = symmetric[model]
        lines.append(
            f"{label} & {_de(f5)} & {_de(s5)} & {_de_signed(s5 - f5)} & "
            f"{_de(f9)} & {_de(s9)} & {_de_signed(s9 - f9)} \\\\"
        )
    lines += [r"\hline", r"\end{tabularx}", ""]
    out_path = OUT / "tab_symhn_pervariant.tex"
    out_path.write_text("\n".join(lines))
    print(f"wrote {out_path}")


def mixed_ap_per_class(suite: str) -> dict[str, float]:
    per_class: dict[str, list[float]] = {c: [] for c in CLASSES}
    pattern = str(SUITES / suite / "model_*/seed_*/det_lora/evaluation.json")
    for path in glob.glob(pattern):
        data = json.load(open(path))
        mixed_history = data["mixed_history"]
        final_task = str(max(int(k) for k in mixed_history))
        ap = mixed_history[final_task]["metrics"].get("AP_per_class@0.5", {})
        for cls in CLASSES:
            if cls in ap:
                per_class[cls].append(ap[cls])
    return {c: st.mean(v) for c, v in per_class.items() if v}


def main() -> None:
    forward = mixed_ap_per_class("thesis_l40_main")
    symmetric = mixed_ap_per_class("thesis_l40_symhn")

    coords_fwd = " ".join(f"({i},{forward[c]:.3f})" for i, c in enumerate(CLASSES))
    coords_sym = " ".join(f"({i},{symmetric[c]:.3f})" for i, c in enumerate(CLASSES))
    xticklabels = ",".join(CLASS_LABEL[c] for c in CLASSES)

    tex = f"""% Generated by code/scripts/make_symhn_figure.py
\\begin{{tikzpicture}}
\\begin{{axis}}[
  thesisplot,
  width=0.96\\textwidth, height=72mm,
  ybar, bar width=10pt,
  xtick={{0,1,2,3,4,5}},
  xticklabels={{{xticklabels}}},
  x tick label style={{rotate=20, anchor=north east, font=\\small}},
  ymin=0, ymax=1.0,
  ylabel={{Gemischte AP@0,5}},
  nodes near coords={{\\pgfmathprintnumber[fixed, fixed zerofill, precision=2, use comma]{{\\pgfplotspointmeta}}}},
  every node near coord/.append style={{font=\\tiny}},
  legend columns=2,
  legend style={{at={{(0.5,1.03)}}, anchor=south}},
]
\\addplot[fill=plotFineTuning, draw=none] coordinates {{{coords_fwd}}};
\\addlegendentry{{forward-only (Iteration 1)}}
\\addplot[fill=plotDetLoRA, draw=none] coordinates {{{coords_sym}}};
\\addlegendentry{{symmetrisch (Iteration 2)}}
\\end{{axis}}
\\end{{tikzpicture}}
"""
    out_path = OUT / "erg_symhn_perclass.tex"
    out_path.write_text(tex, encoding="utf-8")
    print(f"wrote {out_path}")
    write_per_variant_table()
    # console summary of the per-class deltas
    for cls in CLASSES:
        print(
            f"  {cls:22s} {forward[cls]:.3f} -> {symmetric[cls]:.3f}"
            f"  (Δ {symmetric[cls] - forward[cls]:+.3f})"
        )


if __name__ == "__main__":
    main()
