"""Result figures for thesis chapter 7 as native pgfplots graphics, built
from the aggregated L40 suite tables. Axis labels are German because the
figures go into the German thesis; the color and style definitions
(thesisplot, plot* colors) live in master/thesis_main.tex.

Usage (from the repo root):  uv run python scripts/make_thesis_figures.py
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parents[1]
TABLES = REPO / "experiments/analysis/thesis_l40_evaluation_downloaded/tables"
OUT = REPO.parent / "master/abbildungen"
OUT.mkdir(parents=True, exist_ok=True)

MODELS = ["nano", "small", "base", "medium", "large"]
MODEL_LABEL = ["Nano", "Small", "Base", "Medium", "Large"]
METHOD_LABEL = {
    "det_lora": "Det-LoRA",
    "replay": "Replay",
    "cl_detr": "CL-DETR",
    "ewc": "EWC",
    "finetuning": "Fine-Tuning",
    "joint_finetuning": "Joint FT",
}
METHOD_COLOR = {
    "det_lora": "plotDetLoRA",
    "replay": "plotReplay",
    "cl_detr": "plotCLDETR",
    "ewc": "plotEWC",
    "finetuning": "plotFineTuning",
}

CLDETR_SUITE = REPO / "experiments/suites/thesis_l40_cldetr"

HEADER = "% Generated by code/scripts/make_thesis_figures.py\n"


def de(value: float, precision: int = 3) -> str:
    return f"{value:.{precision}f}".replace(".", ",")


def cldetr_main_frame() -> pd.DataFrame:
    """Per-model rows for CL-DETR from the suite summary, averaged over seeds."""
    summary = json.loads((CLDETR_SUITE / "suite_summary.json").read_text())
    rows = []
    for model in MODELS:
        group = summary["groups"][f"{model}:cl_detr"]
        rows.append(
            {
                "model": model,
                "method": "cl_detr",
                "mixed_mAP@0.5:0.95_mean": group["mixed_metrics"]["mAP@0.5:0.95"]["mean"],
                "mixed_mAP@0.5_mean": group["mixed_metrics"]["mAP@0.5"]["mean"],
            }
        )
    return pd.DataFrame(rows)


def cldetr_extension_row(stage_name: str) -> dict:
    """Per-stage extension deltas for CL-DETR, averaged over all runs."""
    results = json.loads((CLDETR_SUITE / "extend/suite_results.json").read_text())
    target, mixed = [], []
    for key, entries in results["groups"].items():
        _, method, _, stage = key.split(":")
        if method == "cl_detr" and stage == stage_name:
            target += [e["target_extension_delta"]["mAP@0.5"] for e in entries]
            mixed += [e["mixed_extension_delta"]["mAP@0.5"] for e in entries]
    return {
        "method": "cl_detr",
        "stage_name": stage_name,
        "target_delta_mAP@0.5_mean": sum(target) / len(target),
        "mixed_delta_mAP@0.5_mean": sum(mixed) / len(mixed),
    }


def fig_methodenvergleich(main: pd.DataFrame, joint: pd.DataFrame) -> None:
    col = "mixed_mAP@0.5:0.95_mean"
    means = pd.concat([main, cldetr_main_frame()]).groupby("method")[col].mean()
    order = ["finetuning", "ewc", "det_lora", "cl_detr", "replay"]
    joint_val = float(joint[joint["method"] == "joint_finetuning"][col].mean())
    ymax = max(joint_val, max(means[m] for m in order)) * 1.18

    bars = []
    for m in order:
        edge = "draw=black, line width=1.1pt" if m == "det_lora" else "draw=none"
        bars.append(
            f"\\addplot[fill={METHOD_COLOR[m]}, {edge}, bar shift=0pt] "
            f"coordinates {{({METHOD_LABEL[m]},{means[m]:.3f})}};"
        )
    bars_tex = "\n".join(bars)
    xcoords = ",".join(METHOD_LABEL[m] for m in order)

    tex = f"""{HEADER}\\begin{{tikzpicture}}
\\begin{{axis}}[
  thesisplot,
  width=0.88\\textwidth, height=66mm,
  ybar, bar width=17pt,
  symbolic x coords={{{xcoords}}},
  xtick={{{xcoords}}},
  ymin=0, ymax={ymax:.3f},
  ylabel={{mAP@0,5:0,95 (gemischt)}},
  nodes near coords={{\\pgfmathprintnumber[fixed, fixed zerofill, precision=3, use comma]{{\\pgfplotspointmeta}}}},
  every node near coord/.append style={{font=\\scriptsize}},
]
{bars_tex}
\\draw[densely dashed, plotJoint, line width=1pt]
  ({{rel axis cs:0,0}}|-{{axis cs:EWC,{joint_val:.3f}}}) --
  ({{rel axis cs:1,0}}|-{{axis cs:EWC,{joint_val:.3f}}});
\\node[anchor=south east, font=\\scriptsize, plotJoint]
  at ({{rel axis cs:0.99,0}}|-{{axis cs:EWC,{joint_val:.3f}}})
  {{Joint Fine-Tuning (obere Referenz): {de(joint_val)}}};
\\end{{axis}}
\\end{{tikzpicture}}
"""
    (OUT / "erg_methodenvergleich.tex").write_text(tex, encoding="utf-8")


def fig_map_by_model(main: pd.DataFrame, joint: pd.DataFrame) -> None:
    col = "mixed_mAP@0.5_mean"
    style = {
        "det_lora": "plotDetLoRA, line width=1.4pt, mark=*, mark size=2.2pt",
        "replay": "plotReplay, line width=1pt, mark=*, mark size=2pt",
        "ewc": "plotEWC, line width=1pt, mark=*, mark size=2pt",
        "finetuning": "plotFineTuning, line width=1pt, mark=*, mark size=2pt",
    }
    plots = []
    for m in ["det_lora", "replay", "ewc", "finetuning"]:
        sub = main[main["method"] == m].set_index("model").reindex(MODELS)
        coords = " ".join(f"({lab},{v:.3f})" for lab, v in zip(MODEL_LABEL, sub[col].values))
        plots.append(
            f"\\addplot[{style[m]}] coordinates {{{coords}}};\n"
            f"\\addlegendentry{{{METHOD_LABEL[m]}}}"
        )
    js = joint[joint["method"] == "joint_finetuning"].set_index("model").reindex(MODELS)
    coords = " ".join(f"({lab},{v:.3f})" for lab, v in zip(MODEL_LABEL, js[col].values))
    plots.append(
        "\\addplot[plotJoint, densely dashed, line width=1pt, mark=diamond*, "
        "mark size=2.4pt, mark options={solid}] coordinates {" + coords + "};\n"
        "\\addlegendentry{Joint FT}"
    )
    plots_tex = "\n".join(plots)

    tex = f"""{HEADER}\\begin{{tikzpicture}}
\\begin{{axis}}[
  thesisplot,
  width=0.92\\textwidth, height=72mm,
  symbolic x coords={{{",".join(MODEL_LABEL)}}},
  xtick=data,
  ymin=0, ymax=1.0,
  xlabel={{Modellvariante}},
  ylabel={{mAP@0,5 (gemischt)}},
  legend columns=3,
  legend style={{at={{(0.5,-0.22)}}, anchor=north}},
]
{plots_tex}
\\end{{axis}}
\\end{{tikzpicture}}
"""
    (OUT / "erg_map_by_model.tex").write_text(tex, encoding="utf-8")


def fig_extension_stage2(ext: pd.DataFrame) -> None:
    ext = pd.concat([ext, pd.DataFrame([cldetr_extension_row("stage_2")])])
    s2 = ext[ext["stage_name"] == "stage_2"].set_index("method")
    order = [
        "det_lora_grow_freeze",
        "det_lora_warm_start",
        "replay",
        "cl_detr",
        "ewc",
        "finetuning",
    ]
    labels = [
        "{Det-LoRA\\\\Grow-Freeze}",
        "{Det-LoRA\\\\Warm-Start}",
        "Replay",
        "CL-DETR",
        "EWC",
        "Fine-Tuning",
    ]
    target = [float(s2.loc[m, "target_delta_mAP@0.5_mean"]) for m in order]
    mixed = [float(s2.loc[m, "mixed_delta_mAP@0.5_mean"]) for m in order]
    ymin = min(target + mixed) * 1.15
    ymax = max(0.012, max(target + mixed) * 2.4)

    coords_target = " ".join(f"({i},{v:.3f})" for i, v in enumerate(target))
    coords_mixed = " ".join(f"({i},{v:.3f})" for i, v in enumerate(mixed))

    tex = f"""{HEADER}\\begin{{tikzpicture}}
\\begin{{axis}}[
  thesisplot,
  width=0.94\\textwidth, height=74mm,
  ybar=2pt, bar width=9pt,
  xtick={{0,1,2,3,4,5}},
  xticklabels={{{",".join(labels)}}},
  x tick label style={{align=center, font=\\small}},
  ymin={ymin:.3f}, ymax={ymax:.3f},
  scaled y ticks=false,
  ylabel={{$\\Delta$ mAP@0,5 (Stufe 2)}},
  yticklabel style={{/pgf/number format/fixed, /pgf/number format/fixed zerofill, /pgf/number format/precision=2, /pgf/number format/use comma}},
  legend columns=2,
  legend style={{at={{(0.5,1.03)}}, anchor=south}},
]
\\addplot[fill=plotZiel, draw=none] coordinates {{{coords_target}}};
\\addlegendentry{{Zielklasse}}
\\addplot[fill=plotDetLoRA, draw=none] coordinates {{{coords_mixed}}};
\\addlegendentry{{gemischte Retention}}
\\draw[black, line width=0.6pt]
  ({{rel axis cs:0,0}}|-{{axis cs:0,0}}) -- ({{rel axis cs:1,0}}|-{{axis cs:0,0}});
\\end{{axis}}
\\end{{tikzpicture}}
"""
    (OUT / "erg_extension_stage2.tex").write_text(tex, encoding="utf-8")


def write_appendix_table(main: pd.DataFrame, joint: pd.DataFrame) -> None:
    """Write a LaTeX table of mixed mAP@0.5:0.95 per variant and method."""
    col = "mixed_mAP@0.5:0.95_mean"
    main = pd.concat([main, cldetr_main_frame()])
    methods = ["det_lora", "replay", "cl_detr", "ewc", "finetuning"]

    def cell(df: pd.DataFrame, meth: str, model: str) -> str:
        v = df[(df["method"] == meth) & (df["model"] == model)][col]
        return f"{v.iloc[0]:.3f}".replace(".", ",") if len(v) else "--"

    rows = [
        r"\begin{tabularx}{\textwidth}{@{}l*{6}{>{\centering\arraybackslash}X}@{}}",
        r"\hline",
        r"\textbf{Variante} & \textbf{Det-LoRA} & \textbf{Replay} & \textbf{CL-DETR} "
        r"& \textbf{EWC} & \textbf{Fine-Tuning} & \textbf{Joint FT} \\",
        r"\hline",
    ]
    for model, lab in zip(MODELS, MODEL_LABEL):
        vals = " & ".join(cell(main, m, model) for m in methods)
        jv = cell(joint, "joint_finetuning", model)
        rows.append(f"{lab} & {vals} & {jv} \\\\")
    rows += [r"\hline", r"\end{tabularx}", ""]
    (OUT / "tab_per_variant_results.tex").write_text("\n".join(rows), encoding="utf-8")


def main() -> None:
    main_df = pd.read_csv(TABLES / "main_summary.csv")
    joint_df = pd.read_csv(TABLES / "joint_summary.csv")
    ext_df = pd.read_csv(TABLES / "extension_stage_method_overview.csv")

    fig_methodenvergleich(main_df, joint_df)
    fig_map_by_model(main_df, joint_df)
    fig_extension_stage2(ext_df)
    write_appendix_table(main_df, joint_df)
    print("wrote figures to", OUT)
    for p in sorted(OUT.glob("erg_*.tex")):
        print(" -", p.name, p.stat().st_size, "B")


if __name__ == "__main__":
    main()
