"""Figure for design iteration 3 (post-hoc decision layer) as a native
pgfplots graphic: mixed mAP@0.5 of the four configurations with standard
deviation, averaged over five model variants and three seeds, read from the
saved sweep logs. Axis labels are German because the figure goes into the
German thesis; style and color definitions live in master/thesis_main.tex.

Usage (from the repo root):  uv run python scripts/make_gate_figure.py
"""

from __future__ import annotations

import re
import statistics as st
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DATA = REPO / "scripts/ablations/data"
OUT = REPO.parent / "master/abbildungen"
OUT.mkdir(parents=True, exist_ok=True)


def parse(path: Path):
    """Return baseline and gate mixed mAP@0.5 values across all runs in a sweep file."""
    base, gate = [], []
    for line in path.read_text().splitlines():
        m = re.search(r"mAP@\.5=([\d.]+)", line)
        if not m:
            continue
        val = float(m.group(1))
        if line.startswith("dichte Baseline"):
            base.append(val)
        elif line.startswith("gate (penalty=0.5"):
            gate.append(val)
    return base, gate


def main() -> None:
    fwd_base, fwd_gate = parse(DATA / "gate_forward_only_sweep.txt")
    sym_base, sym_gate = parse(DATA / "gate_symmetric_sweep.txt")

    labels = [
        "{forward-only\\\\(Baseline)}",
        "{forward-only\\\\$+$ Gate}",
        "{symmetrisch}",
        "{symmetrisch\\\\$+$ Gate}",
    ]
    series = [fwd_base, fwd_gate, sym_base, sym_gate]
    means = [st.mean(s) for s in series]
    stds = [st.pstdev(s) for s in series]
    colors = ["plotFineTuning", "plotDetLoRA", "plotWarm", "plotJoint"]

    bars = []
    for i, (mean, std, color) in enumerate(zip(means, stds, colors)):
        bars.append(
            f"\\addplot[fill={color}, draw=none, bar shift=0pt, "
            "error bars/.cd, y dir=both, y explicit, error bar style={black}] "
            f"coordinates {{({i},{mean:.3f}) +- (0,{std:.3f})}};"
        )
    bars_tex = "\n".join(bars)

    tex = f"""% Generated by code/scripts/make_gate_figure.py
\\begin{{tikzpicture}}
\\begin{{axis}}[
  thesisplot,
  width=0.82\\textwidth, height=68mm,
  ybar, bar width=22pt,
  xtick={{0,1,2,3}},
  xticklabels={{{",".join(labels)}}},
  x tick label style={{align=center, font=\\small}},
  ymin=0, ymax=0.84,
  ylabel={{Gemischte mAP@0,5}},
  nodes near coords={{\\pgfmathprintnumber[fixed, fixed zerofill, precision=3, use comma]{{\\pgfplotspointmeta}}}},
  every node near coord/.append style={{font=\\scriptsize, yshift=7pt}},
]
{bars_tex}
\\end{{axis}}
\\end{{tikzpicture}}
"""
    out_path = OUT / "erg_gate_compare.tex"
    out_path.write_text(tex, encoding="utf-8")
    print(f"wrote {out_path}  (n per bar = {len(fwd_base)})")
    for lab, m, s in zip(labels, means, stds):
        print(f"  {lab:32} {m:.4f} ± {s:.4f}")


if __name__ == "__main__":
    main()
