"""Confusion matrices of the mixed Det-LoRA inference as native TikZ
heatmaps, built from the cached per-image test detections that also feed
the bootstrap analysis (experiments/probes/gate_posthoc_cache). Detections
are thresholded at the per-class F1-optimal confidence (the tab:erg_aux
convention) and greedily matched to ground truth at IoU >= 0.5 regardless
of class, so cross-class label confusion becomes visible. Axis labels are
German because the figures go into the German thesis; color definitions
(plotDetLoRA etc.) live in master/thesis_main.tex.

Usage (from the repo root):  uv run python scripts/make_confusion_figure.py
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import torch

from det_lora.evaluation.metrics import compute_iou_matrix

REPO = Path(__file__).resolve().parents[1]
CACHE = REPO / "experiments/probes/gate_posthoc_cache"
OUT = REPO.parent / "master/abbildungen"
OUT.mkdir(parents=True, exist_ok=True)

CLASS_IDS = [91, 92, 93, 94, 95, 96]
CLASS_LABEL = ["Panzer", "Mil. LKW", "Mil. Flgz.", "Helikopter", "Ziv. PKW", "Ziv. Flgz."]
MODELS = ["nano", "small", "base", "medium", "large"]
SEEDS = [42, 43, 44]
IOU_T = 0.5

HEADER = "% Generated by code/scripts/make_confusion_figure.py\n"


def f1_optimal_thresholds(predictions, ground_truths) -> dict[int, float]:
    """Per-class F1-maximizing confidence threshold at IoU 0.5 (tab:erg_aux)."""
    thresholds: dict[int, float] = {}
    for cid in CLASS_IDS:
        scores, tps = [], []
        n_gt = 0
        for pred, gt in zip(predictions, ground_truths):
            gt_mask = gt["labels"] == cid
            gt_boxes = gt["boxes"][gt_mask]
            n_gt += len(gt_boxes)
            pred_mask = pred["labels"] == cid
            p_boxes = pred["boxes"][pred_mask]
            p_scores = pred["scores"][pred_mask]
            order = np.argsort(-p_scores)
            taken = np.zeros(len(gt_boxes), dtype=bool)
            for idx in order:
                tp = 0
                if len(gt_boxes):
                    ious = compute_iou_matrix(p_boxes[idx : idx + 1], gt_boxes)[0]
                    ious[taken] = 0.0
                    best = int(np.argmax(ious))
                    if ious[best] >= IOU_T:
                        taken[best] = True
                        tp = 1
                scores.append(p_scores[idx])
                tps.append(tp)
        if n_gt == 0 or not scores:
            thresholds[cid] = 1.0
            continue
        scores_arr = np.asarray(scores)
        tps_arr = np.asarray(tps, dtype=np.float64)
        order = np.argsort(-scores_arr)
        cum_tp = np.cumsum(tps_arr[order])
        ranks = np.arange(1, len(order) + 1)
        precision = cum_tp / ranks
        recall = cum_tp / n_gt
        f1 = np.where(precision + recall > 0, 2 * precision * recall / (precision + recall), 0.0)
        thresholds[cid] = float(scores_arr[order][int(np.argmax(f1))])
    return thresholds


def confusion_counts(predictions, ground_truths, thresholds) -> np.ndarray:
    """Rows: GT classes; columns: predicted classes + missed (class-agnostic match)."""
    n = len(CLASS_IDS)
    counts = np.zeros((n, n + 1), dtype=np.int64)
    col = {cid: i for i, cid in enumerate(CLASS_IDS)}
    for pred, gt in zip(predictions, ground_truths):
        keep = np.array(
            [s >= thresholds[int(l)] for s, l in zip(pred["scores"], pred["labels"])], dtype=bool
        )
        p_boxes = pred["boxes"][keep]
        p_scores = pred["scores"][keep]
        p_labels = pred["labels"][keep]
        g_boxes, g_labels = gt["boxes"], gt["labels"]
        taken = np.zeros(len(g_boxes), dtype=bool)
        for idx in np.argsort(-p_scores):
            if not len(g_boxes):
                break
            ious = compute_iou_matrix(p_boxes[idx : idx + 1], g_boxes)[0]
            ious[taken] = 0.0
            best = int(np.argmax(ious))
            if ious[best] >= IOU_T:
                taken[best] = True
                counts[col[int(g_labels[best])], col[int(p_labels[idx])]] += 1
        for g_idx in np.flatnonzero(~taken):
            counts[col[int(g_labels[g_idx])], n] += 1
    return counts


_RUN_CACHE: dict[tuple[str, str, int], np.ndarray] = {}


def run_counts(suite: str, model: str, seed: int) -> np.ndarray:
    key = (suite, model, seed)
    if key not in _RUN_CACHE:
        payload = torch.load(
            str(CACHE / f"{suite}_{model}_seed{seed}_test_nall.pt"), weights_only=False
        )
        preds, gts = payload["predictions"], payload["ground_truths"]
        thresholds = f1_optimal_thresholds(preds, gts)
        _RUN_CACHE[key] = confusion_counts(preds, gts, thresholds)
    return _RUN_CACHE[key]


def aggregate_suite(suite: str, models=MODELS, seeds=SEEDS) -> np.ndarray:
    total = np.zeros((len(CLASS_IDS), len(CLASS_IDS) + 1), dtype=np.int64)
    for model in models:
        for seed in seeds:
            total += run_counts(suite, model, seed)
    return total


def heatmap_tikz(counts: np.ndarray, title: str, y_labels: bool) -> str:
    """One row-normalized confusion heatmap as plain TikZ (percent per GT row)."""
    n = len(CLASS_IDS)
    shares = counts / counts.sum(axis=1, keepdims=True) * 100.0
    cell = 0.94  # cm
    lines = [f"\\begin{{scope}}\n\\node[font=\\small] at ({(n + 1) * cell / 2},{0.55}) {{{title}}};"]
    for r in range(n):
        for c in range(n + 1):
            pct = shares[r, c]
            shade = min(int(round(pct)), 100)
            text_color = "white" if pct >= 55 else "black"
            x, y = c * cell, -(r + 1) * cell
            label = f"{pct:.0f}" if pct >= 0.5 else ("--" if counts[r, c] == 0 else "<1")
            lines.append(
                f"\\fill[plotDetLoRA!{shade}] ({x:.2f},{y:.2f}) rectangle "
                f"({x + cell:.2f},{y + cell:.2f});"
            )
            lines.append(
                f"\\node[font=\\scriptsize, text={text_color}] at "
                f"({x + cell / 2:.2f},{y + cell / 2:.2f}) {{{label}}};"
            )
    lines.append(
        f"\\draw[black!40, very thin] (0,{-n * cell:.2f}) grid[step={cell:.2f}cm] "
        f"({(n + 1) * cell:.2f},0);"
    )
    for c, name in enumerate(CLASS_LABEL + ["verfehlt"]):
        lines.append(
            f"\\node[font=\\scriptsize, rotate=45, anchor=north east] at "
            f"({c * cell + cell * 0.72:.2f},{-n * cell - 0.08:.2f}) {{{name}}};"
        )
    if y_labels:
        for r, name in enumerate(CLASS_LABEL):
            lines.append(
                f"\\node[font=\\scriptsize, anchor=east] at "
                f"(-0.12,{-(r + 1) * cell + cell / 2:.2f}) {{{name}}};"
            )
    lines.append("\\end{scope}")
    return "\n".join(lines)


def write_pair_figure(counts_a: np.ndarray, counts_b: np.ndarray) -> None:
    n = len(CLASS_IDS)
    offset = (n + 1) * 0.94 + 1.55
    tex = (
        HEADER
        + "\\begin{tikzpicture}\n"
        + heatmap_tikz(counts_a, "Iteration 1 (forward-only)", y_labels=True)
        + f"\n\\begin{{scope}}[shift={{({offset:.2f},0)}}]\n"
        + heatmap_tikz(counts_b, "Iteration 4 (finale Konfiguration)", y_labels=False)
        + "\n\\end{scope}\n"
        + "\\end{tikzpicture}\n"
    )
    (OUT / "erg_confusion_matrix.tex").write_text(tex, encoding="utf-8")


def write_appendix_figure(counts: np.ndarray) -> None:
    tex = (
        HEADER
        + "\\begin{tikzpicture}\n"
        + heatmap_tikz(counts, "Iteration 2 (symmetrische Hard Negatives)", y_labels=True)
        + "\n\\end{tikzpicture}\n"
    )
    (OUT / "erg_confusion_iter2.tex").write_text(tex, encoding="utf-8")


def write_joint_figure(counts: np.ndarray) -> None:
    tex = (
        HEADER
        + "\\begin{tikzpicture}\n"
        + heatmap_tikz(counts, "Joint Fine-Tuning (obere Referenz)", y_labels=True)
        + "\n\\end{tikzpicture}\n"
    )
    (OUT / "erg_confusion_joint.tex").write_text(tex, encoding="utf-8")


def per_variant_aircraft_rows() -> list[dict]:
    """Aircraft-pair confusion shares per model variant for the appendix table."""
    rows = []
    mil, civ, missed = 2, 5, len(CLASS_IDS)
    for model in MODELS:
        entry = {"model": model}
        for key, suite in (("iter1", "thesis_l40_main"), ("iter4", "thesis_l40_iter4")):
            counts = aggregate_suite(suite, models=[model])
            share = counts / counts.sum(axis=1, keepdims=True) * 100.0
            entry[key] = {
                "mil_als_civ": share[mil, civ],
                "civ_als_mil": share[civ, mil],
                "mil_diag": share[mil, mil],
                "civ_diag": share[civ, civ],
                "mil_verfehlt": share[mil, missed],
                "civ_verfehlt": share[civ, missed],
            }
        rows.append(entry)
    return rows


def de(value: float, precision: int = 1) -> str:
    return f"{value:.{precision}f}".replace(".", ",")


def write_pervariant_table(rows: list[dict]) -> None:
    """Appendix table: aircraft-pair confusion shares per variant, Iter. 1 vs 4."""
    model_label = {"nano": "Nano", "small": "Small", "base": "Base", "medium": "Medium", "large": "Large"}
    lines = [
        HEADER.rstrip(),
        "\\begin{tabular}{lcccc}",
        "\\hline",
        "\\textbf{Variante} & \\multicolumn{2}{c}{\\textbf{Mil. als Ziv. (\\%)}} & "
        "\\multicolumn{2}{c}{\\textbf{Ziv. als Mil. (\\%)}} \\\\",
        " & It.~1 & It.~4 & It.~1 & It.~4 \\\\",
        "\\hline",
    ]
    for entry in rows:
        lines.append(
            f"{model_label[entry['model']]} & {de(entry['iter1']['mil_als_civ'])} & "
            f"{de(entry['iter4']['mil_als_civ'])} & {de(entry['iter1']['civ_als_mil'])} & "
            f"{de(entry['iter4']['civ_als_mil'])} \\\\"
        )
    lines += ["\\hline", "\\end{tabular}"]
    (OUT / "tab_confusion_pervariant.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    counts_1 = aggregate_suite("thesis_l40_main")
    counts_2 = aggregate_suite("thesis_l40_symhn")
    counts_4 = aggregate_suite("thesis_l40_iter4")
    counts_j = aggregate_suite("baseline_joint")
    write_pair_figure(counts_1, counts_4)
    write_appendix_figure(counts_2)
    write_joint_figure(counts_j)
    write_pervariant_table(per_variant_aircraft_rows())

    summary = {
        "gt_instances_per_run": int(counts_1[:, :].sum() / (len(MODELS) * len(SEEDS))),
        "shares_iter1": (counts_1 / counts_1.sum(axis=1, keepdims=True)).round(4).tolist(),
        "shares_iter2": (counts_2 / counts_2.sum(axis=1, keepdims=True)).round(4).tolist(),
        "shares_iter4": (counts_4 / counts_4.sum(axis=1, keepdims=True)).round(4).tolist(),
        "shares_joint": (counts_j / counts_j.sum(axis=1, keepdims=True)).round(4).tolist(),
        "counts_iter1": counts_1.tolist(),
        "counts_iter4": counts_4.tolist(),
        "per_variant_aircraft": per_variant_aircraft_rows(),
    }
    out_json = REPO / "experiments/analysis/confusion_matrix_summary.json"
    out_json.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print(f"[OK] Figures written to {OUT}, summary to {out_json}")


if __name__ == "__main__":
    main()
